default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: airway_development

test:
  <<: *default
  database: airway_test

production:
  <<: *default
  database: airway_production
  username: airway
# url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['AIRWAY_DATABASE_PASSWORD'] %>
